version: "3.8"

services:
  cpp_project:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: cpp_project_container
    volumes:
      - .:/app
    working_dir: /app
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    tty: true
